baseURL = "https://rikoroku.github.io/"
languageCode = "ja-JP"
title = "rikoroku's portfolio"
theme = "hugo-resume"
publishdir = "public"
canonifyurls = true

[params]
    firstName = "Rikoroku's"
    lastName = "Portfolio"
    address = "Aomori"
    phone = ""
    contactNote = "Freelance web developer" #used in QR code only
    profileImage = "https://avatars3.githubusercontent.com/u/14220000?s=460&v=4"
    email = "rikoroku.55@gmail.com"
    description = ""
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = ""


[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/rikoroku_ja"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/rikoroku"

[[params.handles]]
    name = "Blog"
    link = "https://rikoroku.com"
    icon = "blogger"

[params.google.analytics]
    trackerID = ""

[outputs] #only required for search
    home = ["HTML", "JSON"]
